from launch import LaunchDescription
from launch.actions import SetEnvironmentVariable
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        SetEnvironmentVariable('ROS_LOCALHOST_ONLY', '1'),
        SetEnvironmentVariable('RMW_IMPLEMENTATION', 'rmw_cyclonedds_cpp'),
        Node(
            package='my_drone_vision',
            executable='face_detector',
            name='face_detector_node',
            output='screen',
            parameters=[{
                'video_source': 'tello',
                'face_pose_topic': '/face/pose',
                'cmd_vel_topic': '/cmd_vel',
                'tello_action_service': '/tello_action',
                'frame_width': 640,
                'frame_height': 480,
                'show_window': True,
                'detector_backend': 'yolo',
                'yolo_model_path': 'models/yolov8n-face.pt',
                'yolo_confidence': 0.45,
                'yolo_image_size': 640,
                'yolo_class_id': -1,
                'publish_cmd_vel': False,
                'direct_tello_control': False,
                'auto_takeoff': False,
                'provide_tello_io': True,
                'max_lr_rc': 15,
                'max_fb_rc': 55,
                'max_ud_rc': 18,
                'max_yaw_rc': 35,
                'rc_send_period_sec': 0.10,
            }],
        ),
        Node(
            package='my_drone_vision',
            executable='face_controller',
            name='face_controller_node',
            output='screen',
            parameters=[{
                'face_pose_topic': '/face/pose',
                'cmd_vel_topic': '/cmd_vel',
                'tello_action_service': '/tello_action',
                'auto_takeoff': True,
                'require_face_before_takeoff': True,
                'face_confirm_sec': 2.0,
                'follow_after_takeoff_sec': 2.0,
                'land_on_face_loss': True,
                'face_loss_land_sec': 5.0,
                'target_face_area_ratio': 0.014,
                'forward_area_threshold': 0.013,
                'min_forward_speed': 0.22,
                'deadband_x': 0.075,
                'deadband_y': 0.030,
                'deadband_area': 0.025,
                'pose_filter_alpha': 0.32,
                'max_forward_speed': 0.60,
                'max_vertical_speed': 0.28,
                'max_yaw_speed': 0.36,
                'kp_forward': 2.10,
                'kp_vertical': 0.95,
                'kp_yaw': 0.85,
                'kd_yaw': 0.24,
                'kd_forward': 0.07,
                'lost_timeout_sec': 0.6,
                'search_when_lost': False,
            }],
        ),
    ])
